name: 'JSON propertiy extractor'
description: 'Extract propeties from Json file'
branding:
  icon: sliders
  color: purple
inputs:
  path:
    description: 'The path of the json file.'
    required: true
  properties:
    description: 'The JSON properties to extract.'
    required: true 
  propertyAlias:
    description: 'Property Alias to changed output property name. exmaple: myproperty.subproperty:myalias;autherpro:autheralias'
    required: false 
runs:
  using: 'docker' 
  image: 'docker://ghcr.io/chrisfactory/githubactions:release'
  args:
  - '-p'
  - ${{ inputs.path }}
  - '-v'
  - ${{ inputs.properties }} 
  - '-a'
  - ${{ inputs.propertyAlias }} 